# HorizontalPodAutoscaler: escala segun uso de CPU (escalabilidad - IE2)
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: microservicio-ep3
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: microservicio-ep3
  minReplicas: 2
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
