# ServiceMonitor: le indica al Prometheus Operator que scrapee este servicio.
# Habilita la observabilidad de forma automatizada (IE2).
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: microservicio-ep3
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: microservicio-ep3
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
